[package]
name = "register"
version = "0.1.0"
edition = "2024"

[dependencies]
reqwest = { version = "0.12.23", default-features = false, features = ["blocking", "json", "rustls-tls"] }
serde_json = "1.0.142"
serenity = { version = "0.12.4", default-features = false, features = ["builder"] }
